sudo: required
services:
  - docker

before_install:
  - docker build -t arvini/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run arvini/react-test npm test -- --coverage --watchAll=false

after_success:
  - docker build -t arvini/multi-client ./client
  - docker build -t arvini/multi-nginx ./nginx
  - docker build -t arvini/multi-server ./server
  - docker build -t arvini/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push arvini/multi-client
  - docker push arvini/multi-nginx
  - docker push arvini/multi-server
  - docker push arvini/multi-worker